### ISSUE TITLE
Extract re-used metadata into separate file

### ISSUE THREAD

**Issue by officialdavidtaylor** [officialdavidtaylor/vincit-table-tennis#15]
Looks good. Although I notice the `head` favicon is the same across all the `head.tsx` files. You couuuuld wrap them in a `HeadFavicons` element, but that's just a nitpicky abstraction that isn't technically necessary at all lol.

<img width="303" alt="CleanShot 2022-11-08 at 13 59 29@2x" src="https://user-images.githubusercontent.com/78003700/200684953-90262a1e-22d7-4429-b306-27d02a51fc5e.png">

https://beta.nextjs.org/docs/api-reference/file-conventions/head

> You can import other components that include the allowed <head> tags so you may include defaults with each head.js file that you create for each route.

Sadly you can't nest `head.tsx` files and have it inherit from the one above it ;-;

_Originally posted by @joseph-bravo in https://github.com/officialdavidtaylor/vincit-table-tennis/pull/13#pullrequestreview-1172901166_

**Comment by joseph-bravo** [comment]
Here's the code snippet to extract for reference.

```tsx
      <link rel="apple-touch-icon" href="touch-icon-ipad-retina.png"></link>
      {/* Apple iPhone High Resolution */}
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="touch-icon-iphone-retina.png"
      />
      {/* Apple iPad High Resolution */}
      <link
        rel="apple-touch-icon"
        sizes="167x167"
        href="touch-icon-ipad-retina.png"
      />
      {/* Android Devices High Resolution */}
      <link rel="icon" sizes="192x192" href="touch-icon-hd.png" />
      {/* Android Devices Normal Resolution */}
      <link rel="icon" sizes="128x128" href="touch-icon.png" />
```

**Comment by jojobii-arks** [comment]
holding off for now
